server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false   #通过 eureka.client.registerWithEureka=false 和 fetchRegistry=false 来表明自己是一个eureka server。
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

